name: Build Gradle project
on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    name: Test JVM (${{ matrix.java-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "8", "11", "17", "21" ]
    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DV_ACCESS_KEY }}
      - name: Build with Gradle
        run: ./gradlew clean build -PtestJavaRuntimeVersion=${{ matrix.java-version }}
